### ISSUE TITLE
Report on tests in stryker report (json/html)

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#1565]
Update to the latest mutation testing elements
Gather test run information and provide this data to the report

https://github.com/stryker-mutator/mutation-testing-elements/pull/893

**Tasks**

- [ ] Disable bail from commandline #1784
- [x] Create json report components to hold test data #1802
- [x] Create project components to hold test data #1820
- [ ] Fill test project components with data #1850
- [ ] Save for each mutant which unit test killed it

**Comment by JSmits-utwente** [comment]
For my graduation assignment I need a more complete JSON report from Stryker.NET according to the mutation-testing-elements [schema](https://github.com/stryker-mutator/mutation-testing-elements/blob/master/packages/report-schema/src/mutation-testing-report-schema.json). In particular I need to know for each mutant the properties `killedBy` and `coveredBy`. For this each test case must be given an ID in the report as well. 

If I'm not wrong closing this issue should give me the information I need. How much time / difficulty do you estimate it takes to implement this? If it's not too bad I may pick this up myself.

**Comment by rouke-broersma** [comment]
@JSmits-utwente AFAIK we should already have all this information, we just need to make it available in the report json.

**Comment by rouke-broersma** [comment]
We should make disable-bail available as a cli option so that users can on-demand request a html report with all test information.
